# Generated by Django 4.2.4 on 2023-08-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
