# Generated by Django 4.2.4 on 2023-08-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_platform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.DeleteModel(
            name='UserIncome',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
