# Generated by Django 4.2.4 on 2023-08-24 18:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_product_remove_user_city_delete_userincome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Telegram ID')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], verbose_name='Тип вложения')),
                ('file', models.FileField(upload_to='media/telegram', validators=[core.validators.validate_telegram_media_size], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
