# Generated by Django 4.2.4 on 2023-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=123, max_length=256, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
