# Generated by Django 4.2.3 on 2023-08-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='instant',
        ),
    ]
