# Generated by Django 4.2.4 on 2023-08-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='E-mail')),
                ('telegram_id', models.CharField(max_length=32, unique=True, verbose_name='ID Telegram')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city', verbose_name='Город')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='auth.group', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
